// INCLUDE FILE generated by "Pelles C for Windows, version 1.00".

#define DLG_MAIN			8000
#define IDR_ICO_MAIN		0011
#define IDC_TREE			4000
#define IDC_OPEN			4001
#define IDC_CLOSE			4002
#define IDC_SAVE			4003
#define IDC_SAVENODE		4004
#define IDC_COPY			4005
#define IDC_FILE			4006
#define IDC_PROPGROUP		4007
#define IDC_AUTHOR			5000
#define IDC_TITLE			5001
#define IDC_GENRE			5002
#define IDC_PRICE			5003
#define IDC_PUBLISHED		5004
#define IDC_DESCRIPTION		5005
#define IDC_ISBN			5006

#define IDI_ROOT			1000
#define IDI_ELEMENT			1001
#define IDI_TEXT			1002
#define IDI_ATTRIBUTE		1003
#define IDI_COMENT			1004
#define IDI_DATA			1005
